### ISSUE TITLE
DiskArbitration expiring on Github CI

### ISSUE THREAD

**Issue by PatTheMav** [dmgbuild/dmgbuild#26] opened 2020-11-03 12:56 UTC
This might seem like a bit of a groundhog bug, but from what I could gather this issue might only look like a prior issue regarding detach timeouts:

```
hdiutil: detach: timeout for DiskArbitration expired
hdiutil: detach: drive not detached
hdiutil: detach failed - No such file or directory
hdiutil: detach failed - No such file or directory
hdiutil: detach failed - No such file or directory
hdiutil: detach failed - No such file or directory
hdiutil: detach failed - No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/dmgbuild", line 36, in <module>
    dmgbuild.build_dmg(args.filename, args.volume_name, args.settings, defines=defines, lookForHiDPI=args.lookForHiDPI)
  File "/usr/local/lib/python3.8/site-packages/dmgbuild/core.py", line 614, in build_dmg
    raise DMGError('Unable to detach device cleanly')
dmgbuild.core.DMGError: Unable to detach device cleanly
```

While I'd love to point to CI disk I/O issues as the main culprit, the timing is weird insofar as this never happened with the "old" version (before the Py 3.8 bugfix) and has only occurred since the update.

**Comment by ziyangczi** [comment] 2020-11-07 06:14
we have been patching to have dmgbuild call hdiutil with sudo, not sure if this would work universally, but it has been working for me on appveyor for some reason, see: https://github.com/napari/napari/blob/f0cec79f9de5c5fbd2153a1614b0df2e030e93ae/bundle.py#L102-L110

**Comment by ziyangczi** [comment] 2020-11-07 23:28
I also found that adding a sleep BEFORE the first detach attempt would get rid of the issue mostly, here is a code snippet that does the patch:
```
    from dmgbuild import core

    with open(core.__file__, 'r') as f:
        src = f.read()
    with open(core.__file__, 'w') as f:
        f.write(
            src.replace(
                "shutil.rmtree(os.path.join(mount_point, '.Trashes'), True)",
                "shutil.rmtree(os.path.join(mount_point, '.Trashes'), True);time.sleep(30)",
            )
        )
        print("patched dmgbuild.core")
```

**Comment by ziyangczi** [comment] 2020-11-09 18:50
@al45tair do you feel comfortable adding a CI flag which will enable the sleep before the disk detach? If so I can open a PR

**Comment by al45tair** [comment] 2020-11-09 21:30
It'd be nice to come up with a better solution than sleeping for a random interval. I suppose if it makes it better, I'm open to it, but I'd prefer a more robust fix.

**Comment by tmontes** [comment] 2021-01-19 20:42
Hello all, hello @al45tair,

First and foremost, thanks for dmgbuild -- very nice and very useful! :-)

I've been working on `pup`, a Python GUI application packaging tool that to create MSI installers for Windows and DMG files containing the packaged application bundles for macOS.

I recently stumbled into this issue here: https://github.com/mu-editor/pup/issues/127.

After going through the notes above, I hacked my `pup` / Mu Editor CI PR by forcing `dmgbuild` to retry the `hdiutil detach` more than the default 5 times. This seems to have worked nicely.

Looking at the existing dmgbuild code I note:
* `hdiutil('detach', ...)` is called in a loop up to `detach_retries` times -- in [`dmgbuild/core.py:606`](https://github.com/al45tair/dmgbuild/blob/master/dmgbuild/core.py#L606).
* `detach_retries` is an argument to the `build_dmg` function, with a default value of `5`.
* However, the code in [`scripts/dmgbuild`](https://github.com/al45tair/dmgbuild/blob/master/scripts/dmgbuild#L36) does not pass in `detach_retries`.

Thus, AFAICT, from a CLI usage standpoint, `detach_retries` is hard-coded to 5.

In my CI hack attempt what I did was:
* Forked `dmgbuild`.
* Changed `scripts/dmgbuild` to support an additional `--detach-retries` CLI argument that, in turn, is passed to the `build_dmg` function.
* Forced `pup` to use my `dmgbuild` branch in the CI script.

This has allowed me successfully run `pup` -- and `dmgbuild`! -- on the Mu Editor's CI.

I was wondering if, instead of an arbitrary sleep interval, like you noted above, you would feel such an approach -- supporting a new `--detach-retries` CLI arg -- would be reasonable. If so, I'll happily create a PR implementing just that, as well as addressing other merge critiera you may want.

**Comment by tmontes** [comment] 2021-02-21 23:46
Hi @al45tair, pinging you WRT to my previous note. Would you accept a PR like the one I described?
Thanks again! :-)

**Comment by al45tair** [comment] 2021-05-16 11:43
@tmontes Sorry for taking so long to reply. Yes, I would accept a PR to add a `--detach-retries` flag.

**Comment by al45tair** [comment] 2021-05-31 10:20
I think this might be fixed by #39.

**Comment by tmontes** [comment] 2022-06-25 11:58
@al45tair, its now my turn to take too long to reply. I do confirm that `dmgbuild`'s behaviour on GH Actions is looking good, when using 1.5.2.

Thanks again for `dmgbuild` and for your assistance! :)

**Comment by al45tair** [comment] 2022-06-25 19:13
:-) In the meantime, I'm no longer the maintainer of `dmgbuild`, having handed the baton to @freakboy3742. But it's good to know that this is fixed.

**Comment by freakboy3742** [comment] 2022-11-24 05:08
Closing since @tmontes seems to have confirmed that the issue is resolved.

**Closed by freakboy3742** 2022-11-24 05:08 UTC
